language: node_js
node_js:
- '10'
cache:
- node_modules
sudo: required
addons:
  chrome: stable
notifications:
  email: false
install:
- npm install
script:
- npm run ci
deploy:
  provider: heroku
  api_key:
    secure: UH7J85liblRTFgLEejdaO6OnE5qPOt+OhMd4feZBY0xyJJeFjkcEY4p3Yqyxkuea83nCb5rDNjS0nVBOl7bIsgL7oC8MwKWvocY5QiJ/h/DAzhMYuBrOYH9GqJYk2RY/accoNUC6AcGPLhe8BC2jUZPLfarkT9wnNSoz2ta1bD1YJkUGuqJ55jE5p0Zt9QHIl5FKWQf8TUpylekQ5uHC1mjhRL3evPvMj2liIYCqgjX2xUUS0CCXbacYcdWBKFpS0f9sl8/+bSekKAiDezK03Lvm33ql7O91Su31DdCHj52HPrEYAtDbZW5LfXgvCCcf4LOJCyrvo+saCq92qWRKprwNRqrPTogXFX7Z5Nd/VuWzs0AEFLkLCre5UIjS3mUm2E8YkJjUchE8YQMKNnLN2vzm73p4sXg4jS5r+XYvnZmvIEE4df2Is4NWjvXsWWiG+kDFywpn85H7y2F+1iB9BMnEtJbTdwvXHB5vxrF0JoPiWQ/uM5LnQj4ZROtswqjuDaXkzZAVYiyPq8OLvzEgsHRm6k60vzPP+l2sOaXgvb9/rd4m0dyi6IUfwaYtXkvRIz9Z+KAjUYG2fC7tngjAAuDVSpch/Nmw2hokAIibdPCbMm2TfujbBTohIYIjupjQRyy+VODZlP+w42PfAXgy5PHeOHslEZLmR8HuytgMnlE=
  app: pstm
